### ISSUE TITLE
Please flush stdout after each test run

### ISSUE THREAD

**Issue by mbanck** [jsspencer/testcode#7]
I have the weird problem that the Quantum ESPRESSO testsuite (which uses testcode2 with --verbose) does not print out anything until the main testcode2.py program has finished, at which point the whole output is flushed.

This only happens when building Debian packages with sbuild, as is done on their (and Ubuntu's I believe) autobuilder network.

A solution is to add `sys.stdout.flush()` at the end of the for-loop in `__init__.py:295`:

```
--- ./test-suite/testcode/lib/testcode2/__init__.py.orig        2016-09-23 18:59:05.099035651 +0200
+++ ./test-suite/testcode/lib/testcode2/__init__.py     2016-09-23 18:59:49.855034136 +0200
@@ -302,6 +302,7 @@
                         raise exceptions.RunError(err[0])
                     else:
                         self.verify_job(test_input, test_arg, verbose, rundir)
+                sys.stdout.flush()
         except exceptions.RunError:
             err = sys.exc_info()[1]
             if verbose > 2:
```

**Comment by jsspencer** [comment]
Sorry, @mbanck -- didn't see this until just now. Merged (with a minor addition). Please say if it's still a problem.
